apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    ingressClassName: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: loot.com
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 5000
          - path: /?(.*) # always place client at the end so that ingress can match other routes | if place above, all routes will be send to client-srv
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
